version: '3.8'

services:
  web:
    build: .
    ports:
      - "3010:8080"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
